<?php
//STARTING A SESSION
session_start();

//REQUIERING FILES FROM CORE FOLDER THAT CONTAINS ESSENTIALS FILES FOR THE WEB TO FUNCTIONS EFFICIENTLY
require "../app/core/init.php";

//HERE WE INSTATIATE THE CLASS APP INSIDE THE FOLDER CORE

$app = new App();